### ISSUE TITLE
Send's incorect hours when accept time in next month

### ISSUE THREAD

**Issue by Surzhko** [activebridge/active-bot#1]
Given: 
- in current month `x` working hours
- in next month 'y' working hours
- message was sent in current month with `x` hours

Bot notifies and record's `y` hours  if `Yes` button was pressed in next month

**Comment by Surzhko** [comment]
@igorb Let me know if you need more info

**Comment by igorb** [comment]
9cad40e93127f7892c414da8b98e13968508857d
9aa91eff7dcbc1a0a445773e750ce379e83c6e34
fixed
