### ISSUE TITLE
Multiple responses & duplication in day off list.

### ISSUE THREAD

**Issue by AndriyPedan** [activebridge/active-bot#3]
![bot2](https://user-images.githubusercontent.com/15034023/29212323-a9f12b4e-7ea6-11e7-89bf-310f8d6b9e17.png)
![bot](https://user-images.githubusercontent.com/15034023/29212344-cc2e9548-7ea6-11e7-9415-f65d3b2fca78.png)

**Comment by Alexey-Lukin** [comment]
Vocation should be Vacation

**Comment by igorb** [comment]
fixed
